Override the URL used in demo deployments to match the url used
Override the URL used in demo deployments to match the url used in the
stack.

diff --git a/deploy-deskpro-demo/action.yml b/deploy-deskpro-demo/action.yml
--- a/deploy-deskpro-demo/action.yml
+++ b/deploy-deskpro-demo/action.yml
@@ -137,6 +137,27 @@ runs:
         
         sleep 60
 
+    - name: Lookup MySQL container ID
+      shell: sh
+      id: container
+      run: |
+        service_name="${{ steps.stack-metadata.outputs.stack-name }}_mysql"
+        service_id="$(docker service ps -q "${service_name}" | head -1)"
+        
+        if [ -z "${service_id}" ]; then
+          echo "::error title=Deskpro Swarm service ${service_name} not found::Deskpro Swarm service ${service_name} not found"
+          exit 1
+        fi
+        
+        container_id="$(docker inspect --format '{{.Status.ContainerStatus.ContainerID}}' "${service_id}")"
+        echo "::set-output name=id::${container_id}"
+
+    - name: Update URL setting
+      shell: sh
+      run: |
+        docker exec "${{ steps.container.outputs.id }}" \
+          mysql -A -D deskpro -e "UPDATE settings SET VALUE = '${{ steps.stack-metadata.outputs.url }}' WHERE NAME = 'core.deskpro_url';"
+
     - name: Notify deployment
       shell: bash
       run: |
